### ISSUE TITLE
odbc package

### ISSUE THREAD

**Issue by wjchulme** [opensafely/r-docker#9]
The odbc package is required for making DB connections using ODBC https://cran.r-project.org/web/packages/odbc/index.html
For example so we can submit R scripts via the job-server that connect to the database directly, without extracting data via a study definition.

The package dependencies should all be installed anyway, so it's effectively lightweight.

cc @AnnaB45 @sebbacon

**Comment by sebbacon** [comment]
@bloodearnest agreed this is good to go in

**Comment by bloodearnest** [comment]
Latest R image should have odbc in
